DB_PATH = "luxe_ops.db"
DATE_FMT = "%Y-%m-%d"
NOW_FMT = "%Y-%m-%d %H:%M:%S"

DEFAULT_SETTINGS = {
    "business_name": "Luxe Home Services",
    "tagline": "A higher standard of clean you can feel",
    "phone": "435-994-5348",
    "deep_clean_base_hours": "3",
    "deep_clean_base_price": "320",
    "deep_clean_overage_hourly": "75",
    "recurring_biweekly_rate": "160",
    "max_jobs_per_day": "2",
    "low_pipeline_threshold_14d": "3",
    "self_care_job_threshold_7d": "6",
    "archive_after_days": "180",
    "quote_base_service_low": "40",
    "quote_base_service_high": "55",
    "quote_bedroom_low": "28",
    "quote_bedroom_high": "40",
    "quote_bathroom_low": "35",
    "quote_bathroom_high": "50",
    "quote_living_low": "25",
    "quote_living_high": "38",
    "quote_additional_low": "21.5",
    "quote_additional_high": "31.25",
    "quote_kitchen_small_low": "26",
    "quote_kitchen_small_high": "36",
    "quote_kitchen_medium_low": "32",
    "quote_kitchen_medium_high": "45",
    "quote_kitchen_large_low": "42",
    "quote_kitchen_large_high": "58",
    "quote_deep_multiplier_low": "1.18",
    "quote_deep_multiplier_high": "1.35",
    "quote_moveout_multiplier_low": "1.35",
    "quote_moveout_multiplier_high": "1.55",
    "quote_condition_clean": "0.95",
    "quote_condition_average": "1.00",
    "quote_condition_extra": "1.20",
    "quote_pet_flat_low": "15",
    "quote_pet_flat_high": "30",
    "quote_supplies_low": "10",
    "quote_supplies_high": "18",
    "quote_pantry_org_low": "35",
    "quote_pantry_org_high": "75",
    "sms_provider": "manual_google_voice",
    "sms_enabled": "1",
    "sms_auto_job_reminder": "1",
    "sms_auto_invoice_notice": "1",
    "sms_auto_followup": "0",
}